# Generated by Django 5.1.2 on 2024-10-27 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bouquet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Букет',
                'verbose_name_plural': 'Букеты',
            },
        ),
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Цветок',
                'verbose_name_plural': 'Цветы',
            },
        ),
        migrations.CreateModel(
            name='BouquetFlower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('bouquet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flower_shop.bouquet', verbose_name='Букет')),
                ('flower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flower_shop.flower', verbose_name='Цветок')),
            ],
        ),
        migrations.AddField(
            model_name='bouquet',
            name='flowers',
            field=models.ManyToManyField(through='flower_shop.BouquetFlower', to='flower_shop.flower', verbose_name='Цветы'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Имя клиента')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Телефон клиента')),
                ('order_date', models.DateField(verbose_name='Дата заказа')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая цена')),
                ('bouquet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flower_shop.bouquet', verbose_name='Букет')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
